r-rails/plants

app/models/plant.rb
db/migrate/20220708015711_add_columns_to_plant.rb
db/migrate/20220708103340_create_active_storage_tables.active_storage.rb
db/migrate/20220708111753_remove_img_from_plant.rb
db/schema.rb

Plant model

---

Gemfile.lock
app/controllers/plants_controller.rb
app/helpers/plants_helper.rb
app/views/plants/index.html.haml
app/views/plants/show.html.haml

Plants index page

---

app/controllers/application_controller.rb
app/views/devise/registrations/edit.html.haml
app/views/devise/registrations/new.html.haml
app/views/home/people.html.haml
db/migrate/20220714104052_add_username_to_users.rb
db/schema.rb

add username to users table

---

app/controllers/comments_controller.rb
app/models/comment.rb
app/models/plant.rb
app/models/user.rb
app/views/plants/show.html.haml
config/routes.rb
db/migrate/20220715120525_create_comments.rb
db/schema.rb
test/fixtures/comments.yml
test/models/comment_test.rb

Allow Users to post comments on plants

---

Gemfile
Gemfile.lock
app/assets/stylesheets/application.tailwind.css
app/controllers/plants_controller.rb
app/views/plants/index.html.haml

add ransack search

---

app/views/home/_navbar.html.haml
app/views/partials/_plant_table.html.haml
app/views/plants/index.html.haml
app/views/profile/show.html.haml

Create a Table Partial that can be used to display the list of tables

---

.rspec
app/assets/stylesheets/actiontext.css
app/assets/stylesheets/application.tailwind.css
app/controllers/plants_controller.rb
app/helpers/plants_helper.rb
app/javascript/application.js
app/models/comment.rb
app/views/active_storage/blobs/_blob.html.erb
app/views/comments/_comment.html.haml
app/views/comments/_form.html.haml
app/views/layouts/action_text/contents/_content.html.erb
app/views/plants/_add_plant.html.haml
app/views/plants/show.html.haml
config/importmap.rb
db/migrate/20220725105026_create_action_text_tables.action_text.rb
db/schema.rb

Plant show page reworked.
Action Text is installed to have rich text editor to create comments.

Show page rework

---

.github/workflows/standard.yml
Gemfile
Gemfile.lock
app/models/user.rb
db/migrate/20220725105026_create_action_text_tables.action_text.rb

- User has_one_attached :avatar
- standard up to 1.14.0 version + bundle update

standard gem

---

.github/workflows/standard.yml

- User has_one_attached :avatar
- standard up to 1.14.0 version + bundle update
- rake standard:fix
- standard.yml

standard gem fix

---

app/controllers/application_controller.rb
config/application.rb

Return a user to the page where the login process is started

---

app/controllers/profile_controller.rb
app/helpers/user_helper.rb
app/models/user.rb
config/routes.rb
db/migrate/20220801200923_add_slug_to_user.rb
db/migrate/20220801213646_add_index_to_users.rb
db/schema.rb

Add Friendly ids to user profiles

---

app/views/home/people.html.haml

- start of work
- more work
- people cards alfa version

people page rework

---

app/views/plants/show.html.haml

just minor font size changes and margins because someone of the texts were touching the walls of div :D

change text size, added some margins

---

app/views/profile/show.html.haml
app/views/shared/_header.html.haml

- basic grid
- changed some margins, colors and card styles
- .flex back, so justify-center would work
- add link to profile edit page

add link profile edit

---

app/views/home/people.html.haml
app/views/profile/show.html.haml

remove N+1 queries

---

app/controllers/home_controller.rb
app/controllers/profile_controller.rb
app/models/user.rb
app/views/home/people.html.haml
app/views/profile/show.html.haml

1. Returned pagination to user show page
2. Moved database queries away from the view to the controller

Minor House Keeping

---

app/assets/stylesheets/application.tailwind.css
app/controllers/plants_controller.rb
app/views/plants/_gardenplant_hovercard.html.haml
app/views/profile/show.html.haml

got rid of the hover... because it was over complicating what i wanted to do... which was just a flip with plant info. :3

fixed the flickering 

---

app/controllers/plants_controller.rb
app/views/home/index.html.haml
app/views/plants/top_ten_plants.html.haml
config/routes.rb
spec/factories.rb
spec/system/home_index_spec.rb

This PR is part of the solutions of #146, the `Top 10` tab will substitute the top 10 most added plants into the carousel below it in the layout.

Top ten plants tab

---

app/controllers/home_controller.rb
app/views/home/index.html.haml

- add ransack search variable to the home controller
- add search form to index page

search plants index page

---

app/assets/stylesheets/application.tailwind.css
app/controllers/home_controller.rb
app/controllers/plants_controller.rb
app/javascript/application.js
app/views/home/_active_link_change.html.haml
app/views/home/index.html.haml
app/views/layouts/application.html.haml
app/views/plants/_carousel_for_plants.html.haml
app/views/plants/most_recent_plants.html.haml
app/views/plants/plants_category.html.haml
app/views/plants/top_ten_plants.html.haml
config/environments/test.rb
config/routes.rb
spec/factories.rb
spec/system/home_index_spec.rb

The category tab shows a list of plants category sorted alphabetically, clicking on a category goes to a search page with displaying plants of the category

category tab

---

spec/system/plants_index_spec.rb

system test for plants index page interations

system test for plants index page interations

---

app/controllers/home_controller.rb
app/views/home/_people_partial.html.haml
app/views/home/index.html.haml
app/views/home/people.html.haml
app/views/home/top_growers.html.haml
config/routes.rb
spec/system/home_index_spec.rb

145 growers page from index click

---

app/assets/stylesheets/application.tailwind.css
app/javascript/application.js
app/javascript/controllers/application.js
app/views/home/index.html.haml
app/views/layouts/application.html.haml
app/views/plants/_carousel_for_plants.html.haml
app/views/plants/plants_category.html.haml

143 make carousel dynamic

---

app/controllers/application_controller.rb
app/controllers/notifications_controller.rb
app/controllers/plants_controller.rb
app/models/notification.rb
app/notifications/comment_notification.rb
app/views/comments/_comment.html.haml
app/views/notifications/_notification.html.haml
app/views/notifications/index.html.haml
app/views/shared/_header.html.haml
config/routes.rb

Notification counter

---

app/views/shared/_header.html.haml

- remove pluralize from header
- add bell icon with badge

notification svg

---

app/views/shared/_header.html.haml

resolves minor visual bug caused by Turbo cache

make notifications counter element permanent

---

app/controllers/plants_controller.rb
app/models/notification.rb

Eliminated N+1 queries for getting user notifications for a particular plant

fix n+1 query for notifications

---

app/views/shared/_footer.html.haml

footer colyright date is rendered with ruby code to maintain current year without need for hardcoding

footer date is dynamic

---

.github/workflows/rspec.yml

add rspec.yaml
